# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
u = User.create(email: 'vir@gmail.com', name: 'Vova')
cooking = Category.create(title: 'Cooking')
meat = Test.create(title: 'meat', level: 7, category: cooking, author: u)
steak = Question.create(body: 'how much steak should be cooked?', test: meat)
cutlet = Question.create(body: 'how much cutlet should be cooked?', test: meat)
Answer.create(body: 'seven minutes', correct: true, question: steak)
Answer.create(body: 'ten minutes', correct: true, question: cutlet)
fish = Test.create(title: 'Fish', level: 7, category: cooking, author: u)
salmon = Question.create(body: 'how much salmon is cooked?', test: fish)
perch = Question.create(body: 'how long is the perch salted?', test: fish)
Answer.create(body: '13 minutes', correct: true, question: salmon)
Answer.create(body: 'ten minutes', correct: true, question: perch)

drive = Category.create(title: 'Drive')
drive_a_bike = Test.create(title: 'drive_a_bike', level: 8, category: drive, author: u)
bike = Question.create(body: 'How long does a motorcycle take to reach 100 km/h?', test: drive_a_bike)
cube = Question.create(body: 'What is the volume of cubes in your motorcycle?', test: drive_a_bike)
Answer.create(body: '3,4 sec', correct: true, question: bike)
Answer.create(body: '1000 cub', correct: true, question: cube)
drive_a_car = Test.create(title: 'Drive_a_car', level: 9, category: drive, author: u)
car = Question.create(body: 'when you were traveling by car?', test: drive_a_car)
rules = Question.create(body: 'when you broke the rules in the car?', test: drive_a_car)
Answer.create(body: '2 weeks later', correct: true, question: car)
Answer.create(body: 'rarely', correct: true, question: rules)

game = Category.create(title: 'Game')
rpg = Test.create(title: 'RPG', level: 7, category: game, author: u)
hoeroes = Question.create(body: 'When was the last you played pc?', test: rpg)
cs = Question.create(body: 'when did you play the shooter?', test: rpg)
Answer.create(body: '21 years later', correct: true, question: bike)
Answer.create(body: '1 months later', correct: true, question: cube)
poker = Test.create(title: 'Poker', level: 8, category: game, author: u)
flash = Question.create(body: 'you have collected 5 cards of which suit?', test: rpg)
turn = Question.create(body: 'what matches did you have on the turn?', test: rpg)
Answer.create(body: 'hearts', correct: true, question: flash)
Answer.create(body: '2 king', correct: true, question: turn)

user = User.create(email: 'das@mail.ru', name: 'Sanya')
UserTest.create(user: user, test: meat)
UserTest.create(user: user, test: fish)
UserTest.create(user: user, test: drive_a_bike)
UserTest.create(user: user, test: rpg)
UserTest.create(user: user, test: poker)
